---
- name: Ansible recipe for installing Adafruit_Python_ADS1x15
  hosts: all
  tasks:
    - name: Installs package dependencies
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - build-essential
        - python-dev
        - python-smbus
        - git
        - i2c-tools
        - python-pip
      become: yes
    - name: Downloads Adafruit_Python_ADS1x15 from github
      pip:
        name: adafruit-ads1x15
        state: latest
      become: yes
