---
- name: Ansible recipe for installing Adafruit_Python_ADS1x15
  hosts: all
  tasks:
    - name: Installs package dependencies
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - build-essential
        - python-dev
        - python-smbus
        - git
        - i2c-tools
        - python3-pip
      become: yes
    - name: Downloads Adafruit_Python_ADS1x15 from github
      pip:
        name: adafruit-ads1x15
        state: latest
        executable: pip3
      become: yes
    - name: Enables i2c on Raspberry Pi without using raspi-config
      lineinfile:
        regexp: '#dtparam=i2c_arm=on'
        dest: "/boot/config.txt"
        line: 'dtparam=i2c_arm=on'
        state: present
        backrefs: yes
      ignore_errors: true
      become: yes
      register: i2c_boot_config
    - name: Print reboot needed message after changing i2c configuration
      debug: msg="A Reboot is needed to enable i2c on the Raspberry Pi"
      when: i2c_boot_config.changed
